// ===== WIFI =====
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASS "YOUR_WIFI_PASS"

// ==== SUPABASE CREDENTIALS ====
#define SUPABASE_URL "SUPABASE_URL"  
#define SUPABASE_KEY "YOUR_API_KEY"  
#define SUPABASE_TABLE "TABLE_NAME"